### PR TITLE
Andrew goeden

### PR DESCRIPTION
**Pull request by agoeden12**
hhh

### CODE REVIEW

**Comment by FRC-4509** [comment]
Next time, instead of commenting out a line of deprecated code, just remove it. If we need it, we can just add it in later.

**Comment by FRC-4509** [comment]
Info: This pull request removes our implementation of the now-deprecated RobotDrive and CANTalon, and replaces it with the new Differential Drive and WPI_TalonSRX. Also adds simple TeleOp driving.

**Comment by LTCNugget** [comment]
Has this code been tested?

**Comment by LTCNugget** [comment]
Ready to merge, waiting for testing status.

**Comment by LTCNugget** [comment]
Code runs but TeleOp driving is not implemented yet.

**Pull request merged**
